title: Student Report Generator
logo: /assets/img/logo.png
description: Program outputs a random student report with the parameters specified by the user.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
