title: Student Report Generator
logo: Student_Report_Generator/assets/img/zev_pixels.png
description: Program outputs a random student report with the parameters specified by the user.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
